### ISSUE TITLE
plot.py

### ISSUE THREAD

**Issue by schlaubi666** [solsticedhiver/probemon#1]
if i use the script with this options
   ` "python plot.py --db ~/log/probe_2019_02_03_01_01_01.db -i probe_2019_02_03_01_01_01.png -l -k KNOWNMAC"
`
i only get this error:

```
Traceback (most recent call last):
  File "plot.py", line 186, in <module>
    fig, ax = plt.subplots()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1198, in subplots
    fig = figure(**fig_kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 1044, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1828, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

i run it on kali linux without xorg, and use -i switch to export as image. Why do i get this error ? and how ti fix this ?

**Comment by solsticedhiver** [comment]
First, just a side note:` -k `is to specify mac address like **00:11:22:33:44:55**, not KNOWNMAC.

About the error you got, this is certainly because you don't have xorg installed.
You need to uncomment the 7th line of plot.py to enable the Agg backend of matplotlib (remove the #)

Please tell me if it fixes the problem for you.
